// supabase/functions/_shared/knowledge.ts
// Curated Blueroll guidance notes (reviewed wording). Food safety notes cite the FSA "Safer food, better business" (SFBB)
// section they summarise; premises compliance notes (ids 'premises-*') cite the UK primary sources they were checked against.
// The full SFBB for caterers pack lives in knowledge-sfbb.ts (generated); callers combine both with
// mergeKnowledge(CURATED_KNOWLEDGE, SFBB_KNOWLEDGE) — this file cannot import it at runtime, because these files
// are loaded by Deno (needs '.ts' paths) and by Vitest/tsc (rejects '.ts' paths).
// SFBB © Food Standards Agency, Open Government Licence v3.0. No imports — loaded by Deno and Vitest.
export interface KnowledgeChunk { id: string; title: string; source: string; tags: string[]; text: string }

/** Concatenate knowledge sets in order; a later chunk with an id already seen is dropped. */
export function mergeKnowledge(...sets: KnowledgeChunk[][]): KnowledgeChunk[] {
  const seen = new Set<string>()
  const out: KnowledgeChunk[] = []
  for (const set of sets) for (const c of set) if (!seen.has(c.id)) { seen.add(c.id); out.push(c) }
  return out
}

const SFBB = (section: string) => `FSA Safer food, better business (SFBB) — ${section} (Open Government Licence v3.0)`

// Primary sources for the premises compliance notes (checked October 2026).
const BESA_TR19 = 'BESA — TR19® Grease: kitchen extract ventilation cleaning (thebesa.com/besa-blogs/kitchen-extract-system-cleaning)'
const HSE_CAIS23 = 'HSE — Gas safety in catering and hospitality, CAIS23 (hse.gov.uk/pubns/cais23.pdf)'
const HSE_CAIS10 = 'HSE — Ventilation in catering kitchens, CAIS10 (hse.gov.uk/pubns/cais10.pdf)'
const GOV_FIRE_GUIDE = 'GOV.UK — A guide for persons with duties under fire safety legislation; Regulatory Reform (Fire Safety) Order 2005'
const AVON_LOGBOOK = 'Avon Fire & Rescue Service — Fire safety log book for non-domestic premises (avonfire.gov.uk, 2024)'
const HSE_PAT = 'HSE — Portable appliance testing FAQs (hse.gov.uk/electricity/faq-portable-appliance-testing.htm); Electricity at Work Regulations 1989'

export const CURATED_KNOWLEDGE: KnowledgeChunk[] = [
  { id: 'fridge-temps', title: 'Fridge and freezer temperatures', source: SFBB('Chilling: Chilled storage'),
    tags: ['fridge', 'freezer', 'temperature', 'chilled', 'storage', 'record'],
    text: 'Keep fridges at 5 °C or below (the legal limit is 8 °C) and freezers at −18 °C or below. Check and record each unit at least once a day. If a fridge is above 8 °C, move food to another fridge, check how long it was warm and throw away high-risk food that may be unsafe.' },
  { id: 'probe-calibration', title: 'Checking your probe thermometer', source: SFBB('Management: Temperature probes'),
    tags: ['probe', 'thermometer', 'calibrate', 'calibration', 'accuracy', 'ice', 'boiling'],
    text: 'Check probe accuracy regularly, at least monthly: in iced water it should read between −1 °C and 1 °C, in boiling water between 99 °C and 101 °C. If it reads outside these ranges, replace it or have it recalibrated. Clean and disinfect the probe before and after each use.' },
  { id: 'cooking-core', title: 'Cooking food safely', source: SFBB('Cooking: Cooking safely'),
    tags: ['cook', 'cooking', 'core', 'temperature', '75', 'probe', 'meat', 'poultry'],
    text: 'Cook food until it is steaming hot all the way through. Using a probe, the centre should reach 75 °C (or an equivalent time and temperature such as 70 °C for 2 minutes). Poultry, pork, burgers and sausages must not be pink in the middle.' },
  { id: 'hot-holding', title: 'Keeping food hot', source: SFBB('Cooking: Hot holding'),
    tags: ['hot', 'holding', 'bain-marie', '63', 'service', 'temperature'],
    text: 'Keep hot food at 63 °C or above. Check hot-held food regularly, for example every 2 hours. Food can be kept below 63 °C for one period of up to 2 hours; after that, throw it away.' },
  { id: 'reheating', title: 'Reheating food', source: SFBB('Cooking: Reheating'),
    tags: ['reheat', 'reheating', '75', '82', 'scotland', 'once'],
    text: 'Reheat food until it is steaming hot all the way through: at least 75 °C in the centre in England, Wales and Northern Ireland, and 82 °C in Scotland. Reheat food only once.' },
  { id: 'cooling', title: 'Cooling cooked food', source: SFBB('Chilling: Chilling down hot food'),
    tags: ['cool', 'cooling', 'chill', 'blast', '90', 'minutes', '8'],
    text: 'Cool cooked food to 8 °C or below within 90 minutes, then put it in the fridge. Divide large amounts into smaller portions or shallow trays, or use a blast chiller or ice bath.' },
  { id: 'defrosting', title: 'Defrosting', source: SFBB('Chilling: Defrosting'),
    tags: ['defrost', 'defrosting', 'thaw', 'frozen', 'refreeze'],
    text: 'Defrost food in the fridge where possible, or in a microwave if it will be cooked straight away, or under cold running water. Make sure food is fully defrosted before cooking. Do not refreeze food that has been defrosted unless it has been cooked first.' },
  { id: 'separation', title: 'Separating raw and ready-to-eat food', source: SFBB('Cross-contamination: Separating foods'),
    tags: ['raw', 'ready-to-eat', 'separate', 'cross', 'contamination', 'shelf', 'boards', 'e. coli'],
    text: 'Keep raw meat, poultry, fish and eggs away from ready-to-eat food at all times. Store raw food below ready-to-eat food, ideally in a separate fridge. Use separate boards, knives and equipment, or clean and disinfect them thoroughly between uses.' },
  { id: 'allergens', title: 'Allergen information', source: SFBB('Cross-contamination: Food allergies'),
    tags: ['allergen', 'allergens', '14', 'allergy', 'matrix', 'customer', 'natasha'],
    text: 'You must be able to tell customers which of the 14 regulated allergens are in every dish. Keep allergen information up to date whenever recipes or ingredients change, train staff to ask about allergies and to check the information, and prevent allergen cross-contact when preparing an allergy order.' },
  { id: 'handwashing', title: 'Handwashing', source: SFBB('Cleaning: Handwashing'),
    tags: ['hand', 'handwash', 'basin', 'soap', 'towels', 'wash'],
    text: 'Have a basin used only for handwashing, with hot and cold water, soap and a hygienic way to dry hands. Staff must wash hands before handling food, after handling raw food, after breaks, after using the toilet and after touching bins or cleaning.' },
  { id: 'sanitiser', title: 'Cleaning and disinfecting', source: SFBB('Cleaning: Cleaning effectively'),
    tags: ['sanitiser', 'disinfect', 'bs en 1276', '13697', 'contact time', 'clean'],
    text: 'Use a disinfectant or sanitiser that meets BS EN 1276 or BS EN 13697 and follow the dilution and contact time on the label. Clean first to remove dirt and grease, then disinfect food contact surfaces and equipment.' },
  { id: 'cloths', title: 'Cloths', source: SFBB('Cross-contamination: Cloths'),
    tags: ['cloth', 'cloths', 'towel', 'single-use', '90'],
    text: 'Use single-use cloths where possible, especially for raw food areas. Reusable cloths must be washed on a hot wash (for example 90 °C) between uses. Dirty cloths spread bacteria.' },
  { id: 'pests', title: 'Pest control', source: SFBB('Cross-contamination: Pest control'),
    tags: ['pest', 'pests', 'mice', 'rats', 'flies', 'droppings', 'contractor'],
    text: 'Check regularly for signs of pests such as droppings, gnaw marks and insects. Keep doors and windows proofed and food covered and off the floor. If you find signs of pests, stop using affected areas and food, and call a pest control contractor.' },
  { id: 'illness', title: 'Staff illness', source: SFBB('Cross-contamination: Personal hygiene'),
    tags: ['ill', 'illness', 'sick', 'vomiting', 'diarrhoea', '48', 'exclusion'],
    text: 'Staff must tell a manager if they are ill. Food handlers with vomiting or diarrhoea must not work with food until 48 hours after symptoms have stopped.' },
  { id: 'deliveries', title: 'Checking deliveries', source: SFBB('Management: Suppliers and stock control'),
    tags: ['delivery', 'deliveries', 'supplier', 'reject', 'chilled', 'frozen'],
    text: 'Check deliveries on arrival: chilled food at 5 °C or below (8 °C maximum) and frozen food should arrive at −18 °C or colder — reject it if it is warmer than −15 °C. Check packaging is intact and dates are acceptable. Reject food that is not right and put chilled and frozen food away quickly.' },
  { id: 'review', title: '4-weekly review', source: SFBB('Management: Diary and 4-weekly review'),
    tags: ['review', '4-weekly', 'diary', 'records', 'sign'],
    text: 'Every four weeks, review your safe methods and records: note any problems and what you did, and update your methods when you change your menu, suppliers, equipment or staff.' },
  { id: 'blueroll-checklists', title: 'How Blueroll checklists work', source: 'Blueroll help',
    tags: ['blueroll', 'checklist', 'activate', 'enable', 'app', 'records'],
    text: 'Checklists created by the setup questionnaire start switched off. Review them in Checklists and switch on the ones you want. Completed checklists are your daily diary records and can be exported for an inspection.' },
  { id: 'eho-inspection', title: 'What an inspector looks at', source: 'Blueroll help, based on the FSA Food Hygiene Rating Scheme',
    tags: ['inspection', 'eho', 'inspector', 'rating', 'hygiene', 'score'],
    text: 'An environmental health officer checks how hygienically food is handled, the condition of the premises, and how food safety is managed — including whether you have documented safe methods (such as SFBB) and keep records.' },

  // ── UK premises compliance (England & Wales unless stated). Each note separates what the law requires from
  // recommended / industry practice and cites the primary source(s) it was checked against (October 2026).
  { id: 'premises-extract-duct-cleaning', title: 'How often to clean kitchen extract ductwork (TR19)',
    source: `${BESA_TR19}; ${HSE_CAIS23}`,
    tags: ['duct', 'ductwork', 'ducting', 'extract', 'extractor', 'extraction', 'canopy', 'hood', 'fan', 'grease', 'tr19', 'clean', 'deep clean', 'how often', 'frequency', 'fire'],
    text: 'Grease builds up inside extract ductwork and is a common cause of kitchen fires. No law sets a fixed cleaning interval, but the industry standard, BESA TR19 Grease, gives minimum intervals by how many hours a day the extract is used: heavy use (12–16 hours) every 3 months, moderate use (6–12 hours) every 6 months, light use (2–6 hours) every 12 months. Clean more often if your cooking is very greasy (for example frying, charcoal or wok cooking) or your contractor measures heavy deposits. The whole system should be cleaned by a specialist contractor: canopy, plenum, fan and the full length of ductwork, which needs access panels along its length.' },
  { id: 'premises-extract-duct-law', title: 'Is extract duct cleaning a legal requirement?',
    source: `Regulation (EC) 852/2004 (retained) Annex II, Chapter I (legislation.gov.uk/eur/2004/852/annex/II); ${GOV_FIRE_GUIDE}; ${BESA_TR19}`,
    tags: ['duct', 'ductwork', 'extract', 'extractor', 'law', 'legal', 'required', 'requirement', 'tr19', 'fire', 'risk assessment', 'ventilation'],
    text: 'The law does not name a duct-cleaning frequency or a specific certificate. What the law requires: food hygiene law says food premises must be kept clean and in good repair and have suitable and sufficient ventilation; fire safety law (the Regulatory Reform (Fire Safety) Order 2005 in England and Wales, the Fire (Scotland) Act 2005 in Scotland) requires the responsible person to assess and reduce fire risks, and grease in ductwork is a recognised kitchen fire risk. In practice, cleaning to BESA TR19 Grease is how businesses, fire inspectors and insurers judge whether that risk is controlled. TR19 is an industry standard, not legislation.' },
  { id: 'premises-extract-duct-certificate', title: 'Extract duct cleaning certificate and insurance',
    source: BESA_TR19,
    tags: ['duct', 'ductwork', 'extract', 'certificate', 'cert', 'report', 'post-clean', 'insurance', 'insurer', 'tr19', 'contractor', 'proof'],
    text: 'After a TR19 clean, a competent contractor should give you a post-clean report: before-and-after photos taken from the same positions, grease deposit measurements, notes of any areas they could not reach, and a certificate. BESA describes the target as keeping grease deposits below an average of 200 microns between cleans. Keep these reports with your fire safety records. This is industry practice, not a legal form, but many commercial insurance policies require extract cleaning to TR19, and failing to keep it up can put a claim at risk, so check your policy wording. BESA runs a register of certified kitchen extract cleaning contractors (Vent Hygiene Elite).' },
  { id: 'premises-extract-filters', title: 'Cleaning canopy grease filters',
    source: `${BESA_TR19}; ${HSE_CAIS10}`,
    tags: ['filter', 'filters', 'grease', 'canopy', 'hood', 'extract', 'extractor', 'baffle', 'clean', 'daily', 'staff'],
    text: 'Grease filters in the canopy should be easy to take out and should be cleaned and degreased regularly by your staff, daily or as the manufacturer instructs (BESA guidance). Wipe canopy surfaces as part of your cleaning schedule. Filters do not stop all grease: vapour still passes into the ductwork, so cleaning filters does not replace a specialist TR19 duct clean. HSE guidance says mechanical ventilation should be kept in efficient working order following the manufacturer’s or installer’s instructions. Do not cook on gas appliances with the extract switched off.' },
  { id: 'premises-gas-safety-check', title: 'Gas safety check for commercial kitchens: how often',
    source: `${HSE_CAIS23}; Gas Safety (Installation and Use) Regulations 1998, reg. 35`,
    tags: ['gas', 'gas safety', 'gas safe', 'check', 'inspection', 'service', 'servicing', 'annual', 'engineer', 'cooker', 'oven', 'range', 'appliance', 'how often'],
    text: 'The law requires employers to make sure gas appliances, flues, pipework and safety devices are maintained in a safe condition (regulation 35 of the Gas Safety (Installation and Use) Regulations 1998), and only a Gas Safe registered engineer may do gas work, including inspection and servicing. The law does not fix an interval: HSE says frequency should follow the manufacturer’s recommendations, but as a general rule an annual inspection is a reasonable minimum, with repairs as needed. Check your engineer’s Gas Safe ID card covers commercial catering. Train staff to spot obvious faults (damaged pipework, flame failure devices not working, smell of gas) and to call an engineer straight away rather than waiting for the next service.' },
  { id: 'premises-gas-certificate', title: 'Commercial catering gas safety certificate (CP42)',
    source: `${HSE_CAIS23}; Gas Safety (Installation and Use) Regulations 1998`,
    tags: ['gas', 'certificate', 'cert', 'cp42', 'gas safety', 'record', 'insurance', 'landlord', 'inspection', 'proof'],
    text: 'After inspecting a commercial kitchen, a Gas Safe engineer usually issues a catering gas safety record, often called a CP42. The regulations require safe maintenance by a Gas Safe registered engineer but do not themselves name a CP42 form; the certificate is the usual way to show you have met that duty, and insurers, landlords and inspectors commonly ask for an in-date one (renewed after the annual inspection HSE treats as a reasonable minimum). Keep the latest record with your safety documents. Separately, if you provide accommodation (for example staff rooms or guest rooms), landlord rules apply: those appliances must be checked every 12 months and occupants given the record.' },
  { id: 'premises-gas-interlock', title: 'Gas interlock with the kitchen extract',
    source: `${HSE_CAIS23}; ${HSE_CAIS10}; BS 6173`,
    tags: ['gas', 'interlock', 'extract', 'ventilation', 'fan', 'canopy', 'bs 6173', 'shut off', 'carbon monoxide'],
    text: 'Where gas cooking relies on mechanical extraction, an interlock should cut the gas supply if the extract fan fails, so fumes and carbon monoxide cannot build up. HSE guidance says installers should fit one in line with BS 6173 and that manual bypasses of an interlock are not permitted. BS 6173 is a British Standard, not the law, and it is not retrospective, so older kitchens may not have one. If yours does not, HSE says assess whether a risk arises and control it, for example with a competent engineer’s assessment, good maintenance and clear notices that appliances must not be used without the extract running.' },
  { id: 'premises-fire-risk-assessment', title: 'Fire risk assessment for a food business',
    source: `${GOV_FIRE_GUIDE}; Building Safety Act 2022 s.156 (in force 1 Oct 2023, England and Wales)`,
    tags: ['fire', 'fire risk assessment', 'risk assessment', 'fra', 'responsible person', 'law', 'record', 'review', 'fire safety'],
    text: 'In England and Wales the Regulatory Reform (Fire Safety) Order 2005 requires the responsible person (usually the employer or whoever controls the premises, often the company) to carry out a fire risk assessment and put fire precautions in place. Since 1 October 2023 the whole assessment and your fire safety arrangements must be recorded in writing whatever the size of the business; the old rule that only businesses with five or more employees had to write it down no longer applies. You must also record who carried it out. Review it regularly and whenever something significant changes, such as a refit, new cooking equipment or a change of layout. You can do it yourself if competent, or use a fire risk assessor.' },
  { id: 'premises-fire-scotland', title: 'Fire safety law in Scotland',
    source: 'Scottish Government — Carrying out and recording a fire safety risk assessment (gov.scot, 2021); Fire (Scotland) Act 2005; Fire Safety (Scotland) Regulations 2006',
    tags: ['fire', 'scotland', 'scottish', 'fire risk assessment', 'duty holder', 'record', 'law'],
    text: 'In Scotland fire safety in businesses is covered by the Fire (Scotland) Act 2005 and the Fire Safety (Scotland) Regulations 2006, not the England and Wales Fire Safety Order. Duty holders (employers and anyone with control of the premises) must carry out and review a fire safety risk assessment. A written record is legally required only in certain circumstances, but Scottish Government guidance says keeping a record is useful in all cases to show compliance, so write it down. Northern Ireland has its own separate fire safety legislation; check with the Northern Ireland Fire and Rescue Service.' },
  { id: 'premises-fire-alarm', title: 'Fire alarm testing: weekly test and 6-monthly service',
    source: `${AVON_LOGBOOK}; BS 5839-1`,
    tags: ['fire', 'fire alarm', 'alarm', 'smoke', 'detector', 'call point', 'test', 'testing', 'weekly', 'service', 'six monthly', 'bs 5839'],
    text: 'Fire safety law requires fire alarm systems to be maintained and tested, but the frequencies come from the British Standard BS 5839-1, which fire and rescue services use as the benchmark. Recommended practice: test the alarm weekly during working hours by operating a manual call point, using a different call point each week, and record the result in your fire log book. A competent fire alarm engineer should inspect and service the system at least every six months and give you a certificate. Act on any faults straight away. Small premises without a full alarm system should follow what their fire risk assessment says.' },
  { id: 'premises-emergency-lighting', title: 'Emergency lighting tests: monthly and annual',
    source: `${AVON_LOGBOOK}; BS 5266-1`,
    tags: ['emergency lighting', 'emergency light', 'lights', 'exit sign', 'test', 'testing', 'monthly', 'annual', 'full duration', '3 hour', 'bs 5266'],
    text: 'Emergency lighting must be maintained as part of your fire precautions; the testing routine comes from the British Standard BS 5266-1, which fire and rescue services use as the benchmark. Recommended practice: once a month, briefly switch each emergency light and illuminated exit sign to battery (by simulating a mains failure) and check every one lights, then record it. Once a year, a competent person should carry out a full-duration test, running the lights on battery for their full rated time (often 3 hours), and service the system. Do the annual test when the premises will not be occupied straight afterwards, because batteries need time to recharge.' },
  { id: 'premises-fire-extinguishers', title: 'Fire extinguishers and fire blankets: checks and servicing',
    source: `${AVON_LOGBOOK}; BS 5306-3`,
    tags: ['fire', 'extinguisher', 'extinguishers', 'fire blanket', 'wet chemical', 'class f', 'service', 'annual', 'check', 'monthly', 'bs 5306'],
    text: 'Your fire risk assessment decides what fire-fighting equipment you need. Kitchens with deep fat fryers commonly have a wet chemical (Class F) extinguisher and a fire blanket, as water must never be used on burning oil. Recommended practice (BS 5306-3, followed by fire and rescue services): have all extinguishers and fire blankets inspected and serviced annually by a competent person, and check them yourself at least monthly to make sure each is in place, undamaged, not discharged and showing correct pressure. Record checks and services in your fire log book. Train staff in when, and when not, to use them.' },
  { id: 'premises-fire-drills-training', title: 'Fire drills and staff fire training',
    source: `${GOV_FIRE_GUIDE}; ${AVON_LOGBOOK}`,
    tags: ['fire', 'fire drill', 'drill', 'evacuation', 'training', 'staff', 'induction', 'annual'],
    text: 'Fire safety law requires the responsible person to give staff adequate fire safety training when they start and when risks change. Government guidance says there is no set frequency for fire drills, but at least one a year is likely to be necessary; record each drill and what you learned. Staff should know how to raise the alarm, the escape routes, the assembly point, how to turn off gas and the extract in an emergency, and who calls the fire service. Train new starters on their first shift and repeat training periodically, including part-time and evening staff.' },
  { id: 'premises-fire-log-book', title: 'Fire safety log book: what to record',
    source: AVON_LOGBOOK,
    tags: ['fire', 'log book', 'logbook', 'record', 'records', 'fire safety', 'inspection', 'evidence', 'weekly checks'],
    text: 'Keeping a fire safety log book is how you show a fire inspector that equipment is being tested and maintained. Fire and rescue services publish free log books. Record: weekly fire alarm tests, monthly emergency lighting tests, extinguisher checks and annual services, fire drills, staff fire training, contractor certificates (alarm, emergency lighting, kitchen suppression, extract duct cleaning), faults found and when they were fixed. Daily and weekly walk-round checks (escape routes clear, fire doors closing and not wedged open, signs in place) are not mandatory but are good practice. Blueroll checklists can hold these routine checks.' },
  { id: 'premises-kitchen-fire-suppression', title: 'Kitchen fire suppression systems (e.g. Ansul) and sprinklers',
    source: 'BAFE — Kitchen Fire Protection Systems, SP206 (bafe.org.uk); LPCB LPS 1223; ' + AVON_LOGBOOK,
    tags: ['fire', 'suppression', 'ansul', 'wet chemical', 'canopy', 'fryer', 'sprinkler', 'sprinklers', 'service', 'six monthly', 'bafe'],
    text: 'There is no general legal requirement to fit an automatic fire suppression system over cooking equipment; you may need one because your fire risk assessment, landlord or insurer requires it. If you have one, it must be maintained. Industry practice is a service by a competent engineer about every six months, with a certificate each time; the exact interval comes from the manufacturer, your installer and LPCB LPS 1223, so check your contract and insurer. BAFE SP206 is the third-party certification scheme for kitchen fire protection contractors. Sprinkler systems need regular checks and servicing to the relevant standard (BS EN 12845), including quarterly visits by a competent engineer.' },
  { id: 'premises-eicr-fixed-wiring', title: 'Fixed wiring inspection (EICR) for a restaurant',
    source: `${HSE_PAT}; IET Wiring Matters — Periodic inspection or planned maintenance (electrical.theiet.org/media/1609/periodic-inspection-or-planned-maintenance.pdf); BS 7671 / IET Guidance Note 3`,
    tags: ['electrical', 'electric', 'eicr', 'fixed wiring', 'wiring', 'installation', 'periodic inspection', 'electrician', 'certificate', 'five years', 'test'],
    text: 'The Electricity at Work Regulations 1989 require electrical systems to be maintained so as to prevent danger, but do not set an inspection interval. The recognised way to show your fixed wiring is safe is a periodic inspection by a qualified electrician, who issues an Electrical Installation Condition Report (EICR). IET guidance (BS 7671 Guidance Note 3) gives a typical maximum of 5 years between inspections for restaurants and hotels; the electrician may set a shorter date because kitchens are hot, wet and greasy. Insurers and landlords often ask for an in-date EICR. Fix any C1 or C2 (dangerous or potentially dangerous) findings promptly.' },
  { id: 'premises-pat-testing', title: 'PAT testing portable kitchen appliances',
    source: `${HSE_PAT}; HSE INDG236 — Maintaining portable electrical equipment in low-risk environments (hse.gov.uk/pubns/indg236.pdf)`,
    tags: ['pat', 'pat testing', 'portable appliance', 'portable', 'appliance', 'electrical', 'electric', 'plug', 'lead', 'test', 'annual', 'label'],
    text: 'PAT testing is not a legal requirement and the law does not say it must be done every year. The law (Electricity at Work Regulations 1989) requires electrical equipment that could cause injury to be maintained in a safe condition; how and how often is for you to decide based on risk. HSE guidance: staff should look over plugs, leads and casings before use; a competent person should do formal visual inspections; and earthed (Class I) equipment should also have a combined inspection and test. HSE’s suggested starting intervals for low-risk places are 1–2 years for testing earthed equipment, and kitchens are harsher than offices, so shorter intervals may be sensible. Labels and records are not legally required but are useful.' },
  { id: 'premises-espresso-pressure', title: 'Espresso machine boiler inspection (pressure systems)',
    source: 'HSE — Pressure Systems Safety Regulations 2000 (hse.gov.uk/pressure-systems/pssr.htm); HSE INDG178 Written schemes of examination; Stratford-on-Avon District Council — Coffee machines as pressure systems',
    tags: ['espresso', 'coffee', 'coffee machine', 'boiler', 'steam', 'pressure', 'pssr', 'written scheme', 'examination', 'inspection', 'certificate', 'annual'],
    text: 'Commercial espresso machines and other equipment with a steam boiler are covered by the Pressure Systems Safety Regulations 2000, because steam is in scope at any pressure. The law requires a written scheme of examination, drawn up or certified by a competent person, before the machine is used, and examinations of the boiler and its safety devices (such as safety valves) at the intervals the scheme sets. In practice this is usually about once a year; one council guide says at least every 14 months. If you lease the machine, examination may be included in the rental agreement; otherwise your insurer can often recommend a competent person. Keep the certificate.' },
  { id: 'premises-lifts-loler', title: 'Dumb waiters and goods lifts: thorough examination',
    source: 'HSE — Thorough examinations and inspections of lifting equipment (hse.gov.uk/work-equipment-machinery/thorough-examinations-lifting-equipment.htm); Lifting Operations and Lifting Equipment Regulations 1998',
    tags: ['lift', 'lifts', 'dumb waiter', 'dumbwaiter', 'goods lift', 'service lift', 'loler', 'thorough examination', 'inspection', 'six monthly', 'annual', 'insurance'],
    text: 'Lifts used at work, including goods lifts and dumb waiters, are lifting equipment under LOLER 1998. The law requires a thorough examination by a competent person, with a written report, at least every 6 months for equipment that lifts people and every 12 months for other lifting equipment, unless an examination scheme drawn up by a competent person sets different intervals. Many lift inspectors (often arranged through your insurer) examine dumb waiters and service lifts every 6 months, so follow the interval on your last report. Routine servicing by a lift maintenance company is separate from the thorough examination.' },
  { id: 'premises-legionella', title: 'Legionella risk assessment for a restaurant',
    source: 'HSE — Legionnaires’ disease: keeping records (hse.gov.uk/legionnaires/what-you-must-do/keeping-records.htm); HSE ACOP L8 and HSG274',
    tags: ['legionella', 'legionnaires', 'water', 'water system', 'risk assessment', 'hot water', 'cold water', 'tank', 'record', 'review'],
    text: 'Employers and people in control of premises must assess the risk from legionella in their water systems and control it (Health and Safety at Work Act 1974, COSHH and HSE’s Approved Code of Practice L8). Most small restaurants with simple hot and cold water systems can do a straightforward assessment themselves if competent. If you have five or more employees you must record the significant findings. The law does not set a review interval such as yearly; review the assessment whenever there is reason to think it is no longer valid, for example after changes to the water system or how it is used. Keep records for the period they are current and at least 2 years after.' },
  { id: 'premises-water-temperatures', title: 'Hot and cold water temperatures (legionella control)',
    source: 'HSE — Hot and cold water systems (hse.gov.uk/legionnaires/hot-and-cold.htm); HSE — Things to consider (hse.gov.uk/legionnaires/things-to-consider.htm); HSG274',
    tags: ['legionella', 'water', 'hot water', 'cold water', 'temperature', '60', '50', '20', 'flush', 'flushing', 'outlets', 'monthly', 'weekly'],
    text: 'HSE guidance for controlling legionella by temperature: store hot water at 60 °C or above and distribute it so it reaches at least 50 °C at outlets within one minute of running; keep cold water below 20 °C. Check temperatures at representative (sentinel) outlets monthly and flush little-used taps and showers weekly. These are HSE guidance figures, which follow from the legal duty to control the risk. Hot water at these temperatures can scald, so consider warning signs or mixing valves where needed. This is separate from food hygiene rules on hot water for handwashing and cleaning.' },
  { id: 'premises-waste-duty-of-care', title: 'Business waste: duty of care and waste transfer notes',
    source: 'GOV.UK — Dispose of business or commercial waste: waste transfer notes (gov.uk/dispose-business-commercial-waste/waste-transfer-notes); GOV.UK — Hazardous waste: consignment notes; Environmental Protection Act 1990 s.34',
    tags: ['waste', 'rubbish', 'bins', 'waste transfer note', 'transfer note', 'duty of care', 'carrier', 'collection', 'records', '2 years', 'hazardous'],
    text: 'By law every business has a duty of care for its waste: store it safely, use a registered waste carrier (check the public register), and make sure it is not dumped. Each transfer of waste must be covered by a waste transfer note (one annual note can cover regular collections of the same waste). You must keep waste transfer notes for at least 2 years. Hazardous waste, such as some cleaning chemicals or fluorescent tubes, needs a consignment note instead, which producers must keep for 3 years. Your waste contractor normally provides the paperwork; ask for it and file it.' },
  { id: 'premises-waste-recycling-england', title: 'Separating food waste and recycling (Simpler Recycling, England)',
    source: 'GOV.UK — Simpler Recycling: workplace recycling in England (gov.uk/guidance/simpler-recycling-workplace-recycling-in-england)',
    tags: ['waste', 'food waste', 'recycling', 'simpler recycling', 'separate', 'england', 'bins', 'micro', 'law', '2025', '2027'],
    text: 'In England, Simpler Recycling law requires workplaces to separate waste into food waste, dry recycling (plastic, metal, glass, paper and card) and non-recyclable waste, and arrange collections for each. This applied from 31 March 2025 to businesses with 10 or more full-time equivalent employees. Micro-firms with fewer than 10 FTE employees have until 31 March 2027 (volunteers, contractors and self-employed workers do not count). Small amounts of cooking fat and oil can go with food waste; larger amounts need a used cooking oil collection. Never put cooking oil down the drain.' },
  { id: 'premises-waste-scotland-wales', title: 'Food waste rules in Scotland and Wales',
    source: 'Welsh Government — Workplace recycling (gov.wales/workplace-recycling); Zero Waste Scotland — Waste (Scotland) Regulations (zerowastescotland.org.uk/resources/waste-scotland-regulations)',
    tags: ['waste', 'food waste', 'recycling', 'scotland', 'wales', 'welsh', 'scottish', '5kg', 'sewer', 'macerator', 'separate'],
    text: 'Wales: since 6 April 2024 all workplaces must separate recycling (paper and card, glass, metal, plastic and cartons and more), and premises producing more than 5 kg of food waste a week must separate it for collection. Food waste must not be put into the sewer, for example through a macerator. Scotland: under the Waste (Scotland) Regulations 2012, food businesses producing more than 5 kg of food waste a week must present it for separate collection, and food waste must not go to the sewer; premises in designated rural areas are exempt from these food waste rules. Check with your local authority or waste regulator for details.' },
  { id: 'premises-cooking-oil', title: 'Used cooking oil disposal',
    source: 'GOV.UK — Simpler Recycling: workplace recycling in England; Environmental Protection Act 1990 s.34 (duty of care); Water Industry Act 1991 s.111',
    tags: ['oil', 'cooking oil', 'used oil', 'fryer', 'fat', 'fats', 'grease', 'fog', 'drain', 'sink', 'collection', 'waste'],
    text: 'Never pour used cooking oil, fat or grease down sinks or drains. It sets in the sewer and causes blockages and flooding, and putting matter into a public sewer that interferes with its flow is an offence under the Water Industry Act 1991; water companies can take action against businesses that cause blockages. Store used oil in sealed containers and have it collected by a registered waste carrier, keeping the waste transfer notes (at least 2 years). Scrape plates and pans into food waste before washing. Small amounts of fat can go in food waste collections.' },
  { id: 'premises-grease-trap', title: 'Grease traps and grease separators (FOG)',
    source: 'Building Regulations 2010 Approved Document H, para 2.21 (assets.publishing.service.gov.uk); Thames Water — Best practice for food businesses (thameswater.co.uk/wholesale/best-practice-for-food-businesses); Water Industry Act 1991 s.111',
    tags: ['grease trap', 'grease separator', 'grease', 'fog', 'fats', 'drain', 'drainage', 'blockage', 'sewer', 'water company', 'empty', 'service'],
    text: 'Building Regulations guidance (Approved Document H) says drainage serving commercial hot food kitchens should have a grease separator to BS EN 1825 or another effective means of grease removal; this applies to new or altered drainage, so older kitchens may not have one. Your local water company may also require grease management if your premises cause sewer blockages, as it is an offence to discharge matter that blocks a public sewer. If you have a grease trap or separator, have it emptied and maintained as the manufacturer specifies, using a registered waste carrier, and keep the records.' },
  { id: 'premises-pest-control-contract', title: 'Pest control contracts: are they required?',
    source: 'Regulation (EC) 852/2004 (retained) Annex II, Chapter IX para 4 (legislation.gov.uk/eur/2004/852/annex/II); ' + SFBB('Cross-contamination: Pest control'),
    tags: ['pest', 'pests', 'pest control', 'contract', 'contractor', 'visits', 'how often', 'mice', 'rats', 'cockroaches', 'law', 'required'],
    text: 'Food hygiene law requires food businesses to have adequate procedures to control pests. It does not require a pest control contract or set a number of visits. You can meet the duty with your own regular checks for signs of pests, proofing gaps and doors, and good cleaning and storage, calling a contractor when you find a problem. Many food businesses choose a contract with routine visits and a call-out service; the number of visits is set in the contract according to risk. Keep contractor reports and your own checks, as inspectors may ask to see them. A Blueroll checklist can record your routine pest checks.' },
  { id: 'premises-food-hygiene-training', title: 'Food hygiene training and certificates',
    source: 'FSA — Food hygiene for your business (food.gov.uk/business-guidance/food-hygiene-for-your-business); Regulation (EC) 852/2004 (retained) Annex II, Chapter XII',
    tags: ['training', 'food hygiene', 'certificate', 'cert', 'level 2', 'level 3', 'staff', 'food handler', 'qualification', 'course', 'haccp'],
    text: 'In the UK food handlers do not legally need a food hygiene certificate to prepare or sell food. What the law requires is that food handlers are supervised and instructed or trained in food hygiene to a level that suits the work they do, and that the people responsible for your food safety procedures (HACCP or SFBB) are trained in them. Training can be on the job, self-study or earlier experience. A Level 2 food hygiene course is a common, recommended way to show training for food handlers, and many inspectors look for it, but it is not compulsory. Keep training records.' },
  { id: 'premises-first-aid', title: 'First aid at work',
    source: 'HSE — First aid at work: what employers need to do (hse.gov.uk/firstaid/what-employers-need-to-do.htm); Health and Safety (First-Aid) Regulations 1981',
    tags: ['first aid', 'first aider', 'first aid kit', 'first aid box', 'appointed person', 'burns', 'cuts', 'staff', 'law'],
    text: 'The law requires employers to provide adequate first aid equipment, facilities and people, based on a first aid needs assessment that looks at your hazards (in kitchens: burns, cuts, slips), number of staff, shift patterns and accident history. Some small low-risk workplaces need only a stocked first aid box and an appointed person to take charge of first aid arrangements, who does not need formal training. A busy kitchen may decide it needs trained first aiders on every shift. Include brightly coloured waterproof plasters for food handlers and burn dressings, and tell staff where the kit is.' },
  { id: 'premises-hs-poster-insurance', title: 'Health and safety law poster and employers’ liability insurance',
    source: 'HSE — Display the health and safety law poster (hse.gov.uk/simple-health-safety/display.htm); HSE — Employers’ Liability (Compulsory Insurance) Act 1969 (hse.gov.uk/pubns/hse39.htm)',
    tags: ['poster', 'health and safety', 'law poster', 'employers liability', 'insurance', 'certificate', 'display', 'staff', 'law'],
    text: 'If you employ anyone, the law requires you to display the HSE health and safety law poster where workers can easily read it, or give each worker the equivalent leaflet or pocket card. Most employers must also hold employers’ liability insurance with an authorised insurer and display a copy of the current certificate where employees can easily see it; since 1 October 2008 you may display it electronically instead, as long as staff know where to find it and can access it. These apply to every food business with employees, whatever its size.' },
  { id: 'premises-riddor', title: 'Reporting accidents (RIDDOR) and the accident book',
    source: 'HSE — Types of reportable incidents (hse.gov.uk/riddor/types-of-reportable-incidents.htm); RIDDOR 2013 reg. 12 (legislation.gov.uk/uksi/2013/1471/regulation/12)',
    tags: ['riddor', 'accident', 'accident book', 'injury', 'report', 'reporting', 'hse', 'burn', 'slip', 'hospital', 'record'],
    text: 'The law (RIDDOR 2013) requires employers to report certain incidents to HSE: work-related injuries that keep an employee off work or unable to do their normal duties for more than 7 consecutive days (report within 15 days of the accident), specified serious injuries, some occupational diseases and dangerous occurrences, and injuries to customers or other non-workers who are taken directly from the scene to hospital for treatment. Injuries causing more than 3 days off must be recorded, for example in your accident book, though not reported. Keep RIDDOR records for at least 3 years.' },
  { id: 'premises-coshh', title: 'COSHH assessments for cleaning chemicals',
    source: 'HSE — COSHH assessment (hse.gov.uk/coshh/basics/assessment.htm); Control of Substances Hazardous to Health Regulations 2002',
    tags: ['coshh', 'chemicals', 'cleaning chemicals', 'oven cleaner', 'degreaser', 'safety data sheet', 'sds', 'gloves', 'risk assessment', 'record'],
    text: 'The law (COSHH Regulations 2002) requires employers to assess the risks from hazardous substances staff use, such as oven cleaner, degreasers, descalers, dishwasher chemicals and strong sanitisers, and to control them. Use the product labels and safety data sheets from your supplier to identify hazards, then set controls: safer products where possible, correct dilution, ventilation, gloves and eye protection, safe storage away from food, and training. If you have five or more employees you must record the assessment; HSE says writing it down makes sense even if you have fewer. Review it when products or tasks change.' },
]
