// supabase/functions/_shared/knowledge.ts
// Blueroll guidance notes. Each cites the FSA "Safer food, better business" (SFBB) section it summarises.
// SFBB © Food Standards Agency, Open Government Licence v3.0. No imports — loaded by Deno and Vitest.
export interface KnowledgeChunk { id: string; title: string; source: string; tags: string[]; text: string }

const SFBB = (section: string) => `FSA Safer food, better business (SFBB) — ${section} (Open Government Licence v3.0)`

export const KNOWLEDGE: KnowledgeChunk[] = [
  { id: 'fridge-temps', title: 'Fridge and freezer temperatures', source: SFBB('Chilling: Chilled storage'),
    tags: ['fridge', 'freezer', 'temperature', 'chilled', 'storage', 'record'],
    text: 'Keep fridges at 5 °C or below (the legal limit is 8 °C) and freezers at −18 °C or below. Check and record each unit at least once a day. If a fridge is above 8 °C, move food to another fridge, check how long it was warm and throw away high-risk food that may be unsafe.' },
  { id: 'probe-calibration', title: 'Checking your probe thermometer', source: SFBB('Management: Temperature probes'),
    tags: ['probe', 'thermometer', 'calibrate', 'calibration', 'accuracy', 'ice', 'boiling'],
    text: 'Check probe accuracy regularly, at least monthly: in iced water it should read between −1 °C and 1 °C, in boiling water between 99 °C and 101 °C. If it reads outside these ranges, replace it or have it recalibrated. Clean and disinfect the probe before and after each use.' },
  { id: 'cooking-core', title: 'Cooking food safely', source: SFBB('Cooking: Cooking safely'),
    tags: ['cook', 'cooking', 'core', 'temperature', '75', 'probe', 'meat', 'poultry'],
    text: 'Cook food until it is steaming hot all the way through. Using a probe, the centre should reach 75 °C (or an equivalent time and temperature such as 70 °C for 2 minutes). Poultry, pork, burgers and sausages must not be pink in the middle.' },
  { id: 'hot-holding', title: 'Keeping food hot', source: SFBB('Cooking: Hot holding'),
    tags: ['hot', 'holding', 'bain-marie', '63', 'service', 'temperature'],
    text: 'Keep hot food at 63 °C or above. Check hot-held food regularly, for example every 2 hours. Food can be kept below 63 °C for one period of up to 2 hours; after that, throw it away.' },
  { id: 'reheating', title: 'Reheating food', source: SFBB('Cooking: Reheating'),
    tags: ['reheat', 'reheating', '75', '82', 'scotland', 'once'],
    text: 'Reheat food until it is steaming hot all the way through: at least 75 °C in the centre in England, Wales and Northern Ireland, and 82 °C in Scotland. Reheat food only once.' },
  { id: 'cooling', title: 'Cooling cooked food', source: SFBB('Chilling: Chilling down hot food'),
    tags: ['cool', 'cooling', 'chill', 'blast', '90', 'minutes', '8'],
    text: 'Cool cooked food to 8 °C or below within 90 minutes, then put it in the fridge. Divide large amounts into smaller portions or shallow trays, or use a blast chiller or ice bath.' },
  { id: 'defrosting', title: 'Defrosting', source: SFBB('Chilling: Defrosting'),
    tags: ['defrost', 'defrosting', 'thaw', 'frozen', 'refreeze'],
    text: 'Defrost food in the fridge where possible, or in a microwave if it will be cooked straight away, or under cold running water. Make sure food is fully defrosted before cooking. Do not refreeze food that has been defrosted unless it has been cooked first.' },
  { id: 'separation', title: 'Separating raw and ready-to-eat food', source: SFBB('Cross-contamination: Separating foods'),
    tags: ['raw', 'ready-to-eat', 'separate', 'cross', 'contamination', 'shelf', 'boards', 'e. coli'],
    text: 'Keep raw meat, poultry, fish and eggs away from ready-to-eat food at all times. Store raw food below ready-to-eat food, ideally in a separate fridge. Use separate boards, knives and equipment, or clean and disinfect them thoroughly between uses.' },
  { id: 'allergens', title: 'Allergen information', source: SFBB('Cross-contamination: Food allergies'),
    tags: ['allergen', 'allergens', '14', 'allergy', 'matrix', 'customer', 'natasha'],
    text: 'You must be able to tell customers which of the 14 regulated allergens are in every dish. Keep allergen information up to date whenever recipes or ingredients change, train staff to ask about allergies and to check the information, and prevent allergen cross-contact when preparing an allergy order.' },
  { id: 'handwashing', title: 'Handwashing', source: SFBB('Cleaning: Handwashing'),
    tags: ['hand', 'handwash', 'basin', 'soap', 'towels', 'wash'],
    text: 'Have a basin used only for handwashing, with hot and cold water, soap and a hygienic way to dry hands. Staff must wash hands before handling food, after handling raw food, after breaks, after using the toilet and after touching bins or cleaning.' },
  { id: 'sanitiser', title: 'Cleaning and disinfecting', source: SFBB('Cleaning: Cleaning effectively'),
    tags: ['sanitiser', 'disinfect', 'bs en 1276', '13697', 'contact time', 'clean'],
    text: 'Use a disinfectant or sanitiser that meets BS EN 1276 or BS EN 13697 and follow the dilution and contact time on the label. Clean first to remove dirt and grease, then disinfect food contact surfaces and equipment.' },
  { id: 'cloths', title: 'Cloths', source: SFBB('Cross-contamination: Cloths'),
    tags: ['cloth', 'cloths', 'towel', 'single-use', '90'],
    text: 'Use single-use cloths where possible, especially for raw food areas. Reusable cloths must be washed on a hot wash (for example 90 °C) between uses. Dirty cloths spread bacteria.' },
  { id: 'pests', title: 'Pest control', source: SFBB('Cross-contamination: Pest control'),
    tags: ['pest', 'pests', 'mice', 'rats', 'flies', 'droppings', 'contractor'],
    text: 'Check regularly for signs of pests such as droppings, gnaw marks and insects. Keep doors and windows proofed and food covered and off the floor. If you find signs of pests, stop using affected areas and food, and call a pest control contractor.' },
  { id: 'illness', title: 'Staff illness', source: SFBB('Cross-contamination: Personal hygiene'),
    tags: ['ill', 'illness', 'sick', 'vomiting', 'diarrhoea', '48', 'exclusion'],
    text: 'Staff must tell a manager if they are ill. Food handlers with vomiting or diarrhoea must not work with food until 48 hours after symptoms have stopped.' },
  { id: 'deliveries', title: 'Checking deliveries', source: SFBB('Management: Suppliers and stock control'),
    tags: ['delivery', 'deliveries', 'supplier', 'reject', 'chilled', 'frozen'],
    text: 'Check deliveries on arrival: chilled food at 5 °C or below (8 °C maximum) and frozen food should arrive at −18 °C or colder — reject it if it is warmer than −15 °C. Check packaging is intact and dates are acceptable. Reject food that is not right and put chilled and frozen food away quickly.' },
  { id: 'review', title: '4-weekly review', source: SFBB('Management: Diary and 4-weekly review'),
    tags: ['review', '4-weekly', 'diary', 'records', 'sign'],
    text: 'Every four weeks, review your safe methods and records: note any problems and what you did, and update your methods when you change your menu, suppliers, equipment or staff.' },
  { id: 'blueroll-checklists', title: 'How Blueroll checklists work', source: 'Blueroll help',
    tags: ['blueroll', 'checklist', 'activate', 'enable', 'app', 'records'],
    text: 'Checklists created by the setup questionnaire start switched off. Review them in Checklists and switch on the ones you want. Completed checklists are your daily diary records and can be exported for an inspection.' },
  { id: 'eho-inspection', title: 'What an inspector looks at', source: 'Blueroll help, based on the FSA Food Hygiene Rating Scheme',
    tags: ['inspection', 'eho', 'inspector', 'rating', 'hygiene', 'score'],
    text: 'An environmental health officer checks how hygienically food is handled, the condition of the premises, and how food safety is managed — including whether you have documented safe methods (such as SFBB) and keep records.' },
]
