'use client'

import { useState, useMemo } from 'react'
import { useQuery } from '@tanstack/react-query'
import { supabase } from '@/lib/supabase'
import { useAuthStore } from '@/stores/auth-store'
import { Search, Download, Printer, Check } from 'lucide-react'
import { cn } from '@/lib/utils'
import {
  EU_ALLERGENS,
  ALLERGEN_LABELS,
  type EUAllergen,
} from '@/lib/constants'

/** 3-letter codes, aligned to EU_ALLERGENS order. */
const ALLERGEN_CODES: Record<EUAllergen, string> = {
  gluten: 'GLU', crustaceans: 'CRU', eggs: 'EGG', fish: 'FSH',
  peanuts: 'PNT', soybeans: 'SOY', milk: 'MLK', nuts: 'NUT',
  celery: 'CEL', mustard: 'MUS', sesame: 'SES', sulphites: 'SUL',
  lupin: 'LUP', molluscs: 'MOL',
}

function getAllergens(recipe: any): string[] {
  const set = new Set<string>()
  recipe.recipe_ingredients?.forEach((ri: any) => {
    ri.ingredient?.allergens?.forEach((a: string) => set.add(a))
  })
  return Array.from(set)
}

export default function AllergensPage() {
  const business = useAuthStore((s) => s.business)
  const [search, setSearch] = useState('')

  const { data: recipes = [], isLoading } = useQuery({
    queryKey: ['allergen-recipes', business?.id],
    queryFn: async () => {
      if (!business?.id) return []
      const { data, error } = await supabase
        .from('recipes')
        .select(`*, recipe_ingredients ( ingredient:ingredients (name, allergens) )`)
        .eq('business_id', business.id)
        .eq('active', true)
        .order('name')
      if (error) throw error
      return data ?? []
    },
    enabled: !!business?.id,
  })

  const enriched = useMemo(
    () => recipes.map((r: any) => ({ ...r, _allergens: getAllergens(r) })),
    [recipes]
  )
  const filtered = useMemo(
    () => enriched.filter((r: any) => !search || r.name.toLowerCase().includes(search.toLowerCase())),
    [enriched, search]
  )

  // Column totals (across all active recipes, not just the search subset)
  const colTotals = useMemo(() => {
    const t: Record<string, number> = {}
    EU_ALLERGENS.forEach((a) => { t[a] = enriched.filter((r: any) => r._allergens.includes(a)).length })
    return t
  }, [enriched])
  const maxCol = Math.max(1, ...Object.values(colTotals))

  function exportCSV() {
    const header = ['Recipe', ...EU_ALLERGENS.map((a) => ALLERGEN_LABELS[a])]
    const rows = filtered.map((r: any) => [
      r.name,
      ...EU_ALLERGENS.map((a) => (r._allergens.includes(a) ? 'Y' : '')),
    ])
    const csv = [header, ...rows].map((row) => row.map((c: string) => `"${c}"`).join(',')).join('\n')
    const blob = new Blob([csv], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = 'allergen-matrix.csv'; a.click()
    URL.revokeObjectURL(url)
  }

  function handlePrint() {
    let html = `<!DOCTYPE html><html><head><title>${business?.name ?? 'Blueroll'} — Allergen Matrix</title>
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body { font-family: -apple-system, 'Segoe UI', sans-serif; font-size: 10px; color: #16181d; padding: 16px; }
      h1 { font-size: 16px; font-weight: 700; margin-bottom: 2px; }
      .subtitle { font-size: 10px; color: #6b7280; margin-bottom: 12px; }
      table { width: 100%; border-collapse: collapse; }
      th { font-size: 8px; text-transform: uppercase; letter-spacing: 0.3px; color: #6b7280; padding: 4px 3px; border-bottom: 2px solid #e9eaed; text-align: center; }
      th:first-child { text-align: left; min-width: 120px; }
      td { padding: 4px 3px; border-bottom: 1px solid #f3f4f6; text-align: center; font-size: 10px; }
      td:first-child { text-align: left; font-weight: 500; }
      .yes { color: #c8861a; font-weight: 700; font-size: 11px; }
      .footer { margin-top: 16px; font-size: 8px; color: #9ca3af; text-align: center; }
      @media print { body { padding: 8px; } @page { size: landscape; margin: 10mm; } }
    </style></head><body>`
    html += `<h1>${business?.name ?? 'Allergen Matrix'}</h1>`
    html += `<div class="subtitle">${filtered.length} active recipes · 14 EU allergens · Generated ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</div>`
    html += `<table><tr><th>Recipe</th>`
    EU_ALLERGENS.forEach((a) => { html += `<th>${ALLERGEN_CODES[a]}</th>` })
    html += `<th>Total</th></tr>`
    for (const r of filtered) {
      html += `<tr><td>${r.name}</td>`
      EU_ALLERGENS.forEach((a) => { html += r._allergens.includes(a) ? `<td class="yes">✓</td>` : `<td>—</td>` })
      html += `<td>${r._allergens.length || 'Free'}</td></tr>`
    }
    html += `</table><div class="footer">Generated by Blueroll · blueroll.app</div></body></html>`
    const w = window.open('', '_blank')
    if (w) { w.document.write(html); w.document.close(); w.print() }
  }

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h1 className="text-[25px] font-bold leading-tight tracking-[-0.02em] text-foreground">Allergen Matrix</h1>
          <p className="mt-1 text-[13px] text-muted-foreground">EU 14 allergens across {enriched.length} active recipes</p>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={exportCSV} className="inline-flex items-center gap-1.5 rounded-[10px] border border-input bg-card px-3.5 py-2 text-[13px] font-semibold text-foreground transition-colors hover:bg-accent">
            <Download className="h-4 w-4 text-brand" strokeWidth={1.8} /> CSV
          </button>
          <button onClick={handlePrint} className="inline-flex items-center gap-1.5 rounded-[10px] border border-input bg-card px-3.5 py-2 text-[13px] font-semibold text-foreground transition-colors hover:bg-accent">
            <Printer className="h-4 w-4" strokeWidth={1.8} /> PDF
          </button>
        </div>
      </div>

      {/* Toolbar: search + inline legend */}
      <div className="flex flex-wrap items-center gap-4">
        <div className="relative max-w-[380px] flex-1">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <input
            placeholder="Search recipes…"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="h-[38px] w-full rounded-[10px] border border-input bg-card pl-9 pr-3 text-[13px] text-foreground outline-none transition-shadow placeholder:text-muted-foreground focus:border-brand focus:ring-[3px] focus:ring-[rgba(31,157,99,.12)]"
          />
        </div>
        <div className="flex items-center gap-4 text-[12px] text-muted-foreground">
          <span className="inline-flex items-center gap-1.5">
            <span className="flex h-[18px] w-[18px] items-center justify-center rounded-[6px] bg-[#f6e6cf] text-amber"><Check className="h-2.5 w-2.5" strokeWidth={3} /></span>
            contains allergen
          </span>
          <span className="inline-flex items-center gap-1.5">
            <span className="h-[5px] w-[5px] rounded-full bg-[#e7e9ec]" /> free from
          </span>
        </div>
      </div>

      {isLoading ? (
        <div className="flex items-center justify-center py-16 text-[13px] text-muted-foreground">Loading allergen data…</div>
      ) : (
        <>
          {/* Matrix */}
          <div className="overflow-x-auto rounded-[14px] border border-border bg-card shadow-[0_1px_2px_rgba(16,24,40,.04)]">
            <table className="w-full border-collapse text-[13px]" style={{ minWidth: 1010 }}>
              <thead>
                <tr>
                  <th className="sticky left-0 z-20 border-b border-border bg-card px-4 py-3 text-left font-mono text-[10.5px] font-medium uppercase tracking-[0.06em] text-muted-foreground">Recipe</th>
                  {EU_ALLERGENS.map((a) => {
                    const hot = colTotals[a] >= maxCol * 0.55 && colTotals[a] > 0
                    return (
                      <th key={a} title={ALLERGEN_LABELS[a]}
                        className={cn('border-b border-border px-1 py-2.5 text-center align-bottom', hot && 'bg-[#fbf3e6]')}>
                        <span className={cn('block font-mono text-[11px] font-semibold tracking-wide', hot ? 'text-[#b07d1e]' : 'text-foreground')}>{ALLERGEN_CODES[a]}</span>
                        <span className="mt-0.5 block font-mono text-[10px] tabular-nums text-muted-foreground">{colTotals[a]}</span>
                      </th>
                    )
                  })}
                  <th className="sticky right-0 z-20 border-b border-l border-border bg-card px-3 py-3 text-center font-mono text-[10.5px] font-medium uppercase tracking-[0.06em] text-muted-foreground">Total</th>
                </tr>
              </thead>
              <tbody>
                {filtered.length === 0 ? (
                  <tr>
                    <td colSpan={EU_ALLERGENS.length + 2} className="px-4 py-12 text-center text-[13px] text-muted-foreground">
                      No recipes match &ldquo;{search}&rdquo;.
                    </td>
                  </tr>
                ) : filtered.map((r: any) => {
                  const count = r._allergens.length
                  return (
                    <tr key={r.id} className="group">
                      <td className="sticky left-0 z-10 border-b border-border bg-card px-4 py-2.5 font-medium text-foreground group-hover:bg-[#fafbfb]">
                        <span className="flex items-center gap-2.5">
                          <span className={cn('h-1.5 w-1.5 shrink-0 rounded-full', count ? 'bg-[#e7c79a]' : 'bg-brand')} />
                          <span className="truncate">{r.name}</span>
                        </span>
                      </td>
                      {EU_ALLERGENS.map((a) => (
                        <td key={a} className="border-b border-border px-1 py-2.5 text-center group-hover:bg-[#fafbfb]">
                          {r._allergens.includes(a) ? (
                            <span className="inline-flex h-[27px] w-[27px] items-center justify-center rounded-[8px] bg-[#f6e6cf] text-[#c8861a]">
                              <Check className="h-3.5 w-3.5" strokeWidth={2.6} />
                            </span>
                          ) : (
                            <span className="inline-block h-[5px] w-[5px] rounded-full bg-[#e7e9ec]" />
                          )}
                        </td>
                      ))}
                      <td className="sticky right-0 z-10 border-b border-l border-border bg-card px-3 py-2.5 text-center group-hover:bg-[#fafbfb]">
                        {count ? <span className="font-mono text-[12px] font-semibold tabular-nums text-foreground">{count}</span>
                          : <span className="text-[12px] font-semibold text-brand-deep">Free</span>}
                      </td>
                    </tr>
                  )
                })}
              </tbody>
              {filtered.length > 0 && (
                <tfoot>
                  <tr>
                    <td className="sticky left-0 z-10 bg-card px-4 py-2.5 font-mono text-[10.5px] font-medium uppercase tracking-[0.06em] text-muted-foreground">Per allergen</td>
                    {EU_ALLERGENS.map((a) => {
                      const hot = colTotals[a] >= maxCol * 0.55 && colTotals[a] > 0
                      return (
                        <td key={a} className="px-1 py-2.5 text-center">
                          <span className={cn('font-mono text-[12px] font-semibold tabular-nums', colTotals[a] === 0 ? 'text-[#c2c6cc]' : hot ? 'text-[#b07d1e]' : 'text-muted-foreground')}>{colTotals[a]}</span>
                        </td>
                      )
                    })}
                    <td className="sticky right-0 z-10 border-l border-border bg-card px-3 py-2.5" />
                  </tr>
                </tfoot>
              )}
            </table>
          </div>

          {/* Legend */}
          <div className="rounded-[14px] border border-border bg-card p-4 shadow-[0_1px_2px_rgba(16,24,40,.04)]">
            <p className="mb-3 font-mono text-[10.5px] font-medium uppercase tracking-[0.06em] text-muted-foreground">Allergen codes</p>
            <div className="grid grid-cols-2 gap-x-6 gap-y-2 sm:grid-cols-3 lg:grid-cols-4">
              {EU_ALLERGENS.map((a) => (
                <div key={a} className="flex items-center gap-2 text-[12.5px]">
                  <span className="w-9 shrink-0 font-mono text-[11px] font-semibold text-muted-foreground">{ALLERGEN_CODES[a]}</span>
                  <span className="text-foreground">{ALLERGEN_LABELS[a]}</span>
                </div>
              ))}
            </div>
          </div>
        </>
      )}
    </div>
  )
}
